version: '3.4'

services:
  locadoraveiculos:
    image: ${DOCKER_REGISTRY-}locadoraveiculos
    build:
      context: .
      dockerfile: LocadoraVeiculos/Dockerfile

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Senha1234
    ports:
      - "1433:1433"