version: '3.4'

services:
  locadoraveiculos:
    image: ${DOCKER_REGISTRY-}locadoraveiculos
    build:
      context: .
      dockerfile: LocadoraVeiculos/Dockerfile
    depends_on:
      - db
    ports:
      - "8090:80"

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Senha1234!
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
volumes:
  sqlvolume: